# Generated by Django 4.2.5 on 2023-09-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_churrascos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_churrascos.mptopic')),
            ],
            options={
                'verbose_name_plural': 'MpEntries',
            },
        ),
    ]
