# Generated by Django 4.2.5 on 2023-10-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_churrascos', '0006_mpusuariochurrasco_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpusuariochurrasco',
            name='distancia',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpusuariochurrasco',
            name='endereco',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpusuariochurrasco',
            name='latitude',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpusuariochurrasco',
            name='longitude',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
