# Generated by Django 4.2.5 on 2023-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_churrascos', '0007_mpusuariochurrasco_distancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpusuariochurrasco',
            name='kitBebidas',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpusuariochurrasco',
            name='kitCarnes',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpusuariochurrasco',
            name='tipoTransporte',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
